config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :players, only: [:new, :create]

  resources :games, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_one :player

  def player_name
    Player.find(self.player_id).name
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_param)
    @game.player_id = Player.last.id
    if @game.valid?
      @game.save!
      redirect_to games_path
    else
      render action: :new
    end
  end

  private

  def game_param
    params
    .require(:game)
      .permit(
        :one_first,
        :one_second,
        :two_first,
        :two_second,
        :three_first,
        :three_second,
        :four_first,
        :four_second,
        :five_first,
        :five_second,
        :six_first,
        :six_second,
        :seven_first,
        :seven_second,
        :eight_first,
        :eight_second,
        :nine_first,
        :nine_second,
        :ten_first,
        :ten_second,
        :ten_third,
        :final_score
      )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_param)
    if @player.valid?
      @player.save!
      redirect_to new_game_path
    else
      render action: :new
    end
  end

  private

  def player_param
    params.require(:player).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_games_detail.html.erb
<div class="form-container">
  <% @games.each do |game| %>
    <%= form_for game, url: '/games' do |f| %>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <div class="player-name">Player name: <%= game.player_name %></div>
      <div class="table">
        <div class="thead">
          <div class="row">
            <% (1..10).each do |i| %>
              <div class="col"><%= i %></div>
            <% end %>
            <div class="col">total</div>
          </div>
        </div>
        <div class="tbody">
          <div class="row">
            <div class="col">
              <%= f.text_field :one_first, readonly: true %>
              <%= f.text_field :one_second, readonly: true %>
            </div>
            <div class="col">
              <%= f.text_field :two_first, readonly: true %>
              <%= f.text_field :two_second, readonly: true %>
            </div>
            <div class="col">
              <%= f.text_field :three_first, readonly: true %>
              <%= f.text_field :three_second, readonly: true %>
            </div>
            <div class="col">
              <%= f.text_field :four_first, readonly: true %>
              <%= f.text_field :four_second, readonly: true %>
            </div>
            <div class="col">
              <%= f.text_field :five_first, readonly: true %>
              <%= f.text_field :five_second, readonly: true %>
            </div>
            <div class="col">
              <%= f.text_field :six_first, readonly: true %>
              <%= f.text_field :six_second, readonly: true %>
            </div>
            <div class="col">
              <%= f.text_field :seven_first, readonly: true %>
              <%= f.text_field :seven_second, readonly: true %>
            </div>
            <div class="col">
              <%= f.text_field :eight_first, readonly: true %>
              <%= f.text_field :eight_second, readonly: true %>
            </div>
            <div class="col">
              <%= f.text_field :nine_first, readonly: true %>
              <%= f.text_field :nine_second, readonly: true %>
            </div>
            <div class="col">
              <%= f.text_field :ten_first, readonly: true %>
              <%= f.text_field :ten_second, readonly: true %>
              <%= f.text_field :ten_third, readonly: true %>
            </div>
            <div class="cell js-final-score">
              <%= game.final_score %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  <div class="float-left">
    <%= link_to 'Play new game', new_player_path %>
  </div>
  <div class="float-right">
    <%= link_to 'Back to Home', root_path %>
  </div>
</div>

app/views/games/index.html.erb
<% if @games.present? %>
  <h1 class="text-center">Games Summary</h1>
  <%= render partial: 'games_detail', locals: { games: @games } %>
<% else %>
  <h1>You haven't played any game, please play one.</h1>
<% end %>

app/views/games/new.html.erb
<h1 class="text-center">Let's play a new game</h1>
<div class="form-container">
  <%= form_for @game, as: :game, url: '/games' do |f| %>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <div class="table">
      <div class="thead">
        <div class="row">
          <% (1..10).each do |i| %>
            <div class="col"><%= i %></div>
          <% end %>
          <div class="col">total</div>
        </div>
      </div>
      <div class="tbody">
        <div class="row">
            <div class="col">
              <%= f.text_field :one_first, maxlength: 1 %>
              <%= f.text_field :one_second, maxlength: 1 %>
            </div>
          <div class="col">
            <%= f.text_field :two_first, maxlength: 1 %>
            <%= f.text_field :two_second, maxlength: 1 %>
          </div>
          <div class="col">
            <%= f.text_field :three_first, maxlength: 1 %>
            <%= f.text_field :three_second, maxlength: 1 %>
          </div>
          <div class="col">
            <%= f.text_field :four_first, maxlength: 1 %>
            <%= f.text_field :four_second, maxlength: 1 %>
          </div>
          <div class="col">
            <%= f.text_field :five_first, maxlength: 1 %>
            <%= f.text_field :five_second, maxlength: 1 %>
          </div>
          <div class="col">
            <%= f.text_field :six_first, maxlength: 1 %>
            <%= f.text_field :six_second, maxlength: 1 %>
          </div>
          <div class="col">
            <%= f.text_field :seven_first, maxlength: 1 %>
            <%= f.text_field :seven_second, maxlength: 1 %>
          </div>
          <div class="col">
            <%= f.text_field :eight_first, maxlength: 1 %>
            <%= f.text_field :eight_second, maxlength: 1 %>
          </div>
          <div class="col">
            <%= f.text_field :nine_first, maxlength: 1 %>
            <%= f.text_field :nine_second, maxlength: 1 %>
          </div>
          <div class="col">
            <%= f.text_field :ten_first, maxlength: 1 %>
            <%= f.text_field :ten_second, maxlength: 1 %>
            <%= f.text_field :ten_third, maxlength: 1 %>
          </div>
          <div class="cell js-final-score-text">0</div>
          <%= f.hidden_field :final_score, class: 'js-final-score-val', value: 0 %>
        </div>
      </div>
      <div class="tfoot pt-2">
        <div class="row">
          <input type="submit" value="Save this game" class="btn border"/>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="container index-page-container">
  <h1 class="align-middle text-center index-page-header">Welcome to Boying's Bowling Alley</h1>
  <div class="row justify-content-center cl-effect-5">
    <%= link_to new_player_path, class: 'enter-link' do %>
      <span data-hover="Enter">Enter</span>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleBowling</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/_player_new.html.erb
<div class="container text-center new-player-page-container">
  <h4>Tell me who you are</h4>
  <%= form_for player,
                      url: { controller: 'players', action: :create },
                      method: :post,
                      input_html: { class: 'form-inline' } do |f| %>
    <%= f.text_field :name, required: true, class: 'player-name-input' %>
    <%= f.submit "Let's play" %>
    <%= link_to 'Check past games', games_path %>
  <% end %>
  <%= link_to 'Back to Home', root_path %>
</div>

app/views/players/new.html.erb
<div class="form_container">
  <%= render partial: 'player_new', locals: { player: @player } %>
</div>